// Generated by Phase 01-02 extraction. Behavior-preserving move from the index.html monolith.

// Entry module: imports the responsibility modules, reproduces the monolith's top-level
// execution order, installs the window.* export shim (incl. openCompanyProfile), runs init.
import { STATE, applyUrlState } from "./state.js";
import { DATA } from "./data/index.js";
import { render, svg } from "./viz/index.js";
import "./trust/index.js";
import {
  applyFilters, resetFilters, closeCompare, toggleHelp, loadView, deleteView, openCompanyProfile,
  showFatalError, maybeShowOnboarding, updateStatusIndicator, renderTop10List, wireUI,
} from "./ui/index.js";

// Global error surfaces (match monolith).
window.addEventListener("error", (event) => {
  showFatalError("The viewer hit an unexpected error.", event?.message || "");
});
window.addEventListener("unhandledrejection", (event) => {
  const reason = event?.reason?.message || event?.reason || "Unknown promise rejection";
  showFatalError("A background operation failed.", String(reason));
});

// Data contract guard (was inline in the monolith).
if (!DATA || !Array.isArray(DATA.nodes) || !Array.isArray(DATA.links) || !DATA.profiles) {
  showFatalError("Missing or invalid data/top100-map.js");
  throw new Error("Missing or invalid data/top100-map.js");
}

// Hide loading indicator + button-press micro-interactions.
const loadingEl = document.getElementById("loading");
if (loadingEl) loadingEl.style.display = "none";
document.querySelectorAll('#bar button, #companyCard button').forEach((btn) => {
  btn.classList.add('btn-press');
});

// UI event wiring.
wireUI();

// resize listener (matches monolith).
window.addEventListener("resize", () => {
  svg.attr("width", innerWidth).attr("height", innerHeight);
});

// Expose inline-handler functions on window (onclick="" resolves against window).
// openCompanyProfile was NOT on window in the monolith — explicitly added here.
Object.assign(window, {
  toggleHelp, closeCompare, applyFilters, resetFilters, loadView, deleteView, openCompanyProfile,
});

// Init sequence — exact order from the monolith.
applyUrlState();
render();
maybeShowOnboarding();
updateStatusIndicator();
renderTop10List();
