// Generated by Phase 01-02 extraction. Behavior-preserving move from the index.html monolith.

// STATE object + URL serialization + localStorage-safe helpers.
import { DATA } from "./data/index.js";

function safeLoadList(key) {
  try {
    const raw = localStorage.getItem(key);
    if (!raw) return [];
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? parsed : [];
  } catch (_) {
    return [];
  }
}

function safeSaveJSON(key, value) {
  try {
    localStorage.setItem(key, JSON.stringify(value));
  } catch (_) {
    // Ignore storage write failures (private mode/full quota).
  }
}

function safeReadFlag(key) {
  try {
    return localStorage.getItem(key);
  } catch (_) {
    return null;
  }
}

function safeWriteFlag(key, value) {
  try {
    localStorage.setItem(key, value);
  } catch (_) {
    // Ignore storage write failures (private mode/full quota).
  }
}

const STATE = {
  mode: "global",
  symbol: null,
  hoverSymbol: null,
  labelsVisible: true,
  particlesOn: false,
  particleTimer: null,
  settleTimer: null,
  simulation: null,
  nodes: [],
  links: [],
  layerMap: {},
  lockId: null,
  sourceIndex: {},
  compareList: [],
  searchHistory: safeLoadList("searchHistory"),
  filters: { confidence: 'all', type: 'all', verified: 'all' },
  savedViews: safeLoadList("savedViews"),
};

function syncUrlState() {
  const params = new URLSearchParams();
  params.set("mode", STATE.mode);
  if (STATE.symbol) params.set("symbol", STATE.symbol);
  if (STATE.filters.confidence !== "all") params.set("confidence", STATE.filters.confidence);
  if (STATE.filters.type !== "all") params.set("type", STATE.filters.type);
  if (STATE.filters.verified !== "all") params.set("verified", STATE.filters.verified);
  if (STATE.compareList.length) params.set("compare", STATE.compareList.join(","));
  const url = `${location.pathname}?${params.toString()}`;
  history.replaceState(null, "", url);
}

function applyUrlState() {
  const params = new URLSearchParams(location.search);
  const mode = params.get("mode");
  const symbol = params.get("symbol");
  if (mode === "profile" && symbol && DATA.profiles[symbol]) {
    STATE.mode = "profile";
    STATE.symbol = symbol;
  }
  const confidence = params.get("confidence");
  const type = params.get("type");
  const verified = params.get("verified");
  if (["all", "high", "medium", "low"].includes(confidence || "")) STATE.filters.confidence = confidence;
  if (["all", "supplier", "service", "channel", "demand"].includes(type || "")) STATE.filters.type = type;
  if (["all", "verified", "inferred"].includes(verified || "")) STATE.filters.verified = verified;

  const compareRaw = params.get("compare");
  if (compareRaw) {
    STATE.compareList = compareRaw
      .split(",")
      .map((s) => s.trim())
      .filter((s) => DATA.profiles[s])
      .slice(0, 3);
  }
}

export { STATE, syncUrlState, applyUrlState, safeLoadList, safeSaveJSON, safeReadFlag, safeWriteFlag };
