// Generated by Phase 01-02 extraction. Behavior-preserving move from the index.html monolith.

// D3 force simulation, rendering, motion, tooltips, highlighting.
/* global d3 */
import { STATE, syncUrlState } from "../state.js";
import { DATA, asCountryName, graphForMode } from "../data/index.js";
import { updateCompanyCard, updateCompareButton, openProfile, hideSearchPopovers, jump } from "../ui/index.js";

// D3 / SVG singletons (DOM exists at module eval time — modules are deferred).
const W = innerWidth;
const H = innerHeight;
const svg = d3.select("#canvas").attr("width", W).attr("height", H);
const defs = svg.append("defs");
defs.append("marker").attr("id", "a").attr("viewBox", "0 -3 7 6").attr("refX", 16).attr("refY", 0).attr("markerWidth", 4).attr("markerHeight", 4).attr("orient", "auto")
  .append("path").attr("d", "M0,-2.5L7,0L0,2.5").attr("fill", "#2a2a2a");
const g = svg.append("g");
const zoom = d3.zoom().scaleExtent([0.12, 6]).on("zoom", (e) => g.attr("transform", e.transform));
svg.call(zoom);

// DOM render targets owned by viz.
const tt = document.getElementById("tt");
const titleEl = document.getElementById("title");
const subtitleEl = document.getElementById("subtitle");
const hintEl = document.getElementById("hint");
const legendEl = document.getElementById("lg");
const layerEl = document.getElementById("ly");
const countryBtns = document.getElementById("countryBtns");

// Mutable D3 selections — reassigned only inside this module (render), so local `let` is safe.
let nodeSel;
let linkSel;
let labelSel;
let subSel;
let particleLayer;

function animateCounter(elementId, target, duration = 1000, prefix = '', suffix = '') {
  const el = document.getElementById(elementId);
  if (!el) return;
  
  const start = 0;
  const startTime = performance.now();
  const easeOutQuad = t => t * (2 - t);
  
  function update(currentTime) {
    const elapsed = currentTime - startTime;
    const progress = Math.min(elapsed / duration, 1);
    const eased = easeOutQuad(progress);
    const current = Math.floor(start + (target - start) * eased);
    
    el.textContent = prefix + current.toLocaleString() + suffix;
    
    if (progress < 1) {
      requestAnimationFrame(update);
    }
  }
  
  requestAnimationFrame(update);
}

function updateStatsAnimated(nodes, links, countries, layers, marketCap) {
  animateCounter('sN', nodes.length, 800);
  animateCounter('sL', links.length, 800);
  animateCounter('sC', countries, 800);
  animateCounter('sY', layers, 800);
  animateCounter('sM', marketCap, 1000, '$', 'T');
}

function updateStats() {
  const countryCount = new Set(STATE.nodes.map((n) => n.c)).size;
  const layerCount = Object.keys(STATE.layerMap).length;
  const totalCap = STATE.nodes.filter(n => n.marketcap).reduce((sum, n) => sum + n.marketcap, 0);
  const marketCapT = totalCap / 1e12;
  
  // Use animated counter function
  animateCounter('sN', STATE.nodes.length, 800);
  animateCounter('sL', STATE.links.length, 800);
  animateCounter('sC', countryCount, 800);
  animateCounter('sY', layerCount, 800);
  animateCounter('sM', marketCapT, 1000, '$', 'T');
}

function buildLegend() {
  legendEl.innerHTML = "";
  
  // Q6: Node type counts
  const typeCounts = {
    company: STATE.nodes.filter(n => n.kind === 'company').length,
    supplier: STATE.nodes.filter(n => n.kind === 'supplier').length,
    service: STATE.nodes.filter(n => n.kind === 'service').length,
    channel: STATE.nodes.filter(n => n.kind === 'channel').length,
    demand: STATE.nodes.filter(n => n.kind === 'demand').length
  };
  
  const typeHeader = document.createElement('div');
  typeHeader.style.cssText = 'font-size:8px;color:#666;text-transform:uppercase;margin-bottom:4px';
  typeHeader.textContent = 'Node Types';
  legendEl.appendChild(typeHeader);
  
  Object.entries(typeCounts).forEach(([type, count]) => {
    if (count > 0) {
      const li = document.createElement("div");
      li.style.cssText = 'font-size:9px;color:#888;margin-bottom:2px';
      li.innerHTML = `${type}: <b style="color:#aaa">${count}</b>`;
      legendEl.appendChild(li);
    }
  });
  
  // Country section
  const countryHeader = document.createElement('div');
  countryHeader.style.cssText = 'font-size:8px;color:#666;text-transform:uppercase;margin:8px 0 4px';
  countryHeader.textContent = 'Countries';
  legendEl.appendChild(countryHeader);
  
  const used = [...new Set(STATE.nodes.map((n) => n.c))];
  used.forEach((code) => {
    const li = document.createElement("div");
    li.className = "li";
    const color = DATA.countries[code]?.c || "#777";
    li.innerHTML = `<span class="ld" style="background:${color}"></span>${code} ${asCountryName(code)}`;
    legendEl.appendChild(li);
  });
}

function buildLayerSidebar() {
  layerEl.innerHTML = "";
  const keys = [...new Set(STATE.nodes.map((n) => n.layer))].sort((a, b) => a - b);
  keys.forEach((layer) => {
    const b = document.createElement("button");
    b.type = "button";
    b.className = "lb";
    b.textContent = `${layer} / ${STATE.layerMap[layer] || ""}`;
    b.setAttribute("aria-label", `Highlight layer ${layer}`);
    b.onclick = () => highlightBy((n) => n.layer === layer);
    layerEl.appendChild(b);
  });
}

function buildCountryButtons() {
  countryBtns.innerHTML = "";
  if (STATE.mode !== "global") return;
  const counts = d3.rollups(STATE.nodes, (v) => v.length, (d) => d.c).sort((a, b) => b[1] - a[1]).slice(0, 8);
  counts.forEach(([code]) => {
    const b = document.createElement("button");
    b.type = "button";
    b.textContent = code;
    b.setAttribute("aria-label", `Highlight country ${code}`);
    b.onclick = () => highlightBy((n) => n.c === code);
    countryBtns.appendChild(b);
  });
  const all = document.createElement("button");
  all.type = "button";
  all.textContent = "All";
  all.setAttribute("aria-label", "Reset country highlight");
  all.onclick = () => resetHighlight();
  countryBtns.appendChild(all);
}

function clearGraph() {
  if (STATE.simulation) STATE.simulation.stop();
  if (STATE.particleTimer) cancelAnimationFrame(STATE.particleTimer);
  if (STATE.settleTimer) clearTimeout(STATE.settleTimer);
  g.selectAll("*").remove();
  STATE.particleTimer = null;
  STATE.settleTimer = null;
  STATE.particlesOn = false;
  STATE.lockId = null;
  tt.style.display = "none";
}

function showTooltip(d, ev) {
  const tt = document.getElementById('tt');
  
  // Check for source verification
  const confidenceRaw = d.confidence || 'low';
  const confidenceLower = confidenceRaw.toLowerCase();
  let confidenceLevel = 'low';
  if (confidenceLower.includes('high') || confidenceLower.includes('company')) confidenceLevel = 'high';
  else if (confidenceLower.includes('medium') || confidenceLower.includes('source')) confidenceLevel = 'medium';
  
  const verified = confidenceLevel === 'high' || d.sourceId;
  const confidenceClass = `confidence-${confidenceLevel}`;
  const confidenceLabel = confidenceLevel.charAt(0).toUpperCase() + confidenceLevel.slice(1);
  
  // Helper to format value
  const formatValue = (v) => {
    if (typeof v === 'number') {
      if (v >= 1e12) return '$' + (v / 1e12).toFixed(2) + 'T';
      if (v >= 1e9) return '$' + (v / 1e9).toFixed(2) + 'B';
      if (v >= 1e6) return '$' + (v / 1e6).toFixed(2) + 'M';
      return '$' + v.toFixed(2);
    }
    return v;
  };
  
  tt.innerHTML = `
    <div class="tn">${(d.l || d.label || d.id || '').replace("\n", " - ")}</div>
    <div class="tf">${d.kind || 'Node'} · <span class="confidence-badge ${confidenceClass}">${confidenceLabel} Confidence</span></div>
    <div class="td">
      <div class="td-col">
        ${d.country || d.c ? `
          <div class="td-item">
            <span class="td-label">Country</span>
            <span class="td-value">${d.country || asCountryName(d.c)}</span>
          </div>
        ` : ''}
        ${d.type ? `
          <div class="td-item">
            <span class="td-label">Type</span>
            <span class="td-value">${d.type}</span>
          </div>
        ` : ''}
      </div>
      <div class="td-col">
        ${d.value ? `
          <div class="td-item">
            <span class="td-label">Value</span>
            <span class="td-value">${formatValue(d.value)}</span>
          </div>
        ` : ''}
        ${verified ? `
          <div class="td-item">
            <span class="td-label">Source</span>
            <span class="td-value">✓ Verified</span>
          </div>
        ` : ''}
      </div>
    </div>
    ${d.sourceUrl || (d.sourceId && STATE.sourceIndex[d.sourceId]) ? `
      <div class="tu">
        <a href="${d.sourceUrl || STATE.sourceIndex[d.sourceId].url}" target="_blank" rel="noopener" class="source-link">View Source →</a>
      </div>
    ` : ''}
  `;
  
  moveTooltip(ev);
  tt.style.display = 'block';
}

function linkNodeLabel(endpoint) {
  if (!endpoint) return "Unknown";
  const node = typeof endpoint === "object" ? endpoint : STATE.nodes.find((n) => n.id === endpoint);
  if (!node) return "Unknown";
  return (node.l || node.id || "Unknown").split("\n")[0];
}

function showLinkTooltip(d, ev) {
  const tt = document.getElementById('tt');
  
  // Check for source verification
  const confidenceRaw = d.cf || 'low';
  const confidenceLower = confidenceRaw.toLowerCase();
  let confidenceLevel = 'low';
  if (confidenceLower.includes('high') || confidenceLower.includes('company')) confidenceLevel = 'high';
  else if (confidenceLower.includes('medium') || confidenceLower.includes('source')) confidenceLevel = 'medium';
  
  const verified = confidenceLevel === 'high' || d.sf;
  const confidenceClass = `confidence-${confidenceLevel}`;
  const confidenceLabel = confidenceLevel.charAt(0).toUpperCase() + confidenceLevel.slice(1);
  
  tt.innerHTML = `
    <div class="tn">${linkNodeLabel(d.source)} → ${linkNodeLabel(d.target)}</div>
    <div class="tf">Relationship · <span class="confidence-badge ${confidenceClass}">${confidenceLabel} Confidence</span></div>
    <div class="td">
      <div class="td-col">
        <div class="td-item">
          <span class="td-label">Type</span>
          <span class="td-value">${d.k || "flow"}</span>
        </div>
        <div class="td-item">
          <span class="td-label">Weight</span>
          <span class="td-value">${d.v || 1}</span>
        </div>
      </div>
      <div class="td-col">
        <div class="td-item">
          <span class="td-label">Note</span>
          <span class="td-value">${d.n || "Supply-chain relationship"}</span>
        </div>
        ${verified ? `
          <div class="td-item">
            <span class="td-label">Source</span>
            <span class="td-value">✓ Verified</span>
          </div>
        ` : ''}
      </div>
    </div>
    ${d.sf && STATE.sourceIndex[d.sf] ? `
      <div class="tu">
        <a href="${STATE.sourceIndex[d.sf].url}" target="_blank" rel="noopener" class="source-link">View Source →</a>
      </div>
    ` : ''}
  `;
  
  moveTooltip(ev);
  tt.style.display = 'block';
}

function moveTooltip(ev) {
  let x = ev.clientX + 14;
  let y = ev.clientY - 10;
  if (x + 450 > W) x = ev.clientX - 460;
  if (y + 250 > H) y = H - 260;
  tt.style.left = `${x}px`;
  tt.style.top = `${y}px`;
}

function connected(id) {
  const all = new Set([id]);
  const up = new Set();
  const down = new Set();
  STATE.links.forEach((l) => {
    const s = typeof l.source === "object" ? l.source.id : l.source;
    const t = typeof l.target === "object" ? l.target.id : l.target;
    if (s === id) { down.add(t); all.add(t); }
    if (t === id) { up.add(s); all.add(s); }
  });
  return { all, up, down };
}

function highlightNode(d) {
  const conn = connected(d.id);
  nodeSel.select(".mc").transition().duration(150).attr("fill-opacity", (n) => conn.all.has(n.id) ? 0.95 : 0.05);
  labelSel.transition().duration(150).attr("fill-opacity", (n) => conn.all.has(n.id) ? 1 : 0.05);
  subSel.transition().duration(150).attr("fill-opacity", (n) => conn.all.has(n.id) ? 1 : 0.05);
  linkSel.transition().duration(150)
    .attr("stroke-opacity", (l) => {
      const s = typeof l.source === "object" ? l.source.id : l.source;
      const t = typeof l.target === "object" ? l.target.id : l.target;
      return (s === d.id || t === d.id) ? 1 : 0.03;
    })
    .attr("stroke", (l) => {
      const s = typeof l.source === "object" ? l.source.id : l.source;
      const t = typeof l.target === "object" ? l.target.id : l.target;
      if (s === d.id) return "var(--acc)";
      if (t === d.id) return "var(--blue)";
      return "#111";
    })
    .attr("stroke-width", (l) => {
      const s = typeof l.source === "object" ? l.source.id : l.source;
      const t = typeof l.target === "object" ? l.target.id : l.target;
      return (s === d.id || t === d.id) ? 2 : 0.3;
    });
}

function resetHighlight() {
  nodeSel.select(".mc").transition().duration(180).attr("fill-opacity", (d) => d.bn ? 0.82 : 0.35);
  labelSel.transition().duration(180).attr("fill-opacity", 1);
  subSel.transition().duration(180).attr("fill-opacity", STATE.labelsVisible ? 1 : 0);
  linkSel.transition().duration(180)
    .attr("stroke-opacity", 1)
    .attr("stroke", (d) => d.v >= 3 ? "rgba(232,69,60,.18)" : d.v >= 2 ? "#1e1e1e" : "#151515")
    .attr("stroke-width", (d) => d.v >= 3 ? 1.4 : d.v >= 2 ? 0.7 : 0.35);
}

function highlightBy(fn) {
  STATE.lockId = null;
  tt.style.display = "none";
  nodeSel.select(".mc").transition().duration(160).attr("fill-opacity", (d) => fn(d) ? 1 : 0.03);
  labelSel.transition().duration(160).attr("fill-opacity", (d) => fn(d) ? 1 : 0.03);
  subSel.transition().duration(160).attr("fill-opacity", (d) => fn(d) ? (STATE.labelsVisible ? 1 : 0) : 0.03);
  linkSel.transition().duration(160).attr("stroke-opacity", 0.015);
}

function toggleParticles() {
  STATE.particlesOn = !STATE.particlesOn;
  if (!STATE.particlesOn) {
    if (STATE.particleTimer) cancelAnimationFrame(STATE.particleTimer);
    particleLayer.selectAll("*").remove();
    return;
  }
  const step = () => {
    if (!STATE.particlesOn) return;
    const strong = STATE.links.filter((l) => l.v >= 3);
    strong.forEach((l) => {
      if (Math.random() > 0.9) return;
      const s = typeof l.source === "object" ? l.source : STATE.nodes.find((n) => n.id === l.source);
      const t = typeof l.target === "object" ? l.target : STATE.nodes.find((n) => n.id === l.target);
      if (!s || !t) return;
      particleLayer.append("circle").attr("r", 1.2).attr("fill", "var(--acc)").attr("opacity", 0.55).attr("cx", s.x).attr("cy", s.y)
        .transition().duration(1400 + Math.random() * 900).ease(d3.easeLinear)
        .attr("cx", t.x).attr("cy", t.y).attr("opacity", 0).attr("r", 0.4).remove();
    });
    STATE.particleTimer = requestAnimationFrame(() => setTimeout(step, 120));
  };
  step();
}

function render() {
  clearGraph();
  hideSearchPopovers();
  const graph = graphForMode();
  STATE.nodes = graph.nodes;
  STATE.links = graph.links;
  STATE.layerMap = graph.layers;
  STATE.sourceIndex = graph.sourceIndex || {};

  titleEl.innerHTML = STATE.mode === "global"
    ? `<img src="./assets/monarch-logo.png" alt="Monarch Castle Technologies" class="logo"><span class="companyName">Monarch Castle Technologies</span><span class="separator">|</span><span class="tagline">Market Intelligence</span>`
    : `<span>Company Profile</span> / ${STATE.symbol}`;
  subtitleEl.textContent = graph.subtitle;
  hintEl.textContent = graph.hint;
  document.getElementById("bBack").style.display = STATE.mode === "profile" ? "inline-block" : "none";
  jump.value = STATE.mode === "profile" ? STATE.symbol : "";
  document.getElementById("fConfidence").value = STATE.filters.confidence;
  document.getElementById("fType").value = STATE.filters.type;
  document.getElementById("fVerified").value = STATE.filters.verified;
  
  // Update footer with last updated timestamp
  const footerEl = document.getElementById('lastUpdated');
  if (footerEl && DATA.meta?.lastUpdated) {
    footerEl.textContent = DATA.meta.lastUpdated;
  }
  
  updateCompanyCard();
  updateCompareButton();

  updateStats();
  buildLegend();
  buildLayerSidebar();
  buildCountryButtons();

  const layerKeys = [...new Set(STATE.nodes.map((n) => n.layer))].sort((a, b) => a - b);
  const bandH = H / Math.max(1, layerKeys.length);

  layerKeys.forEach((layer, i) => {
    const y = (layerKeys.length - 1 - i) * bandH;
    if (STATE.mode === "global") {
      g.append("rect").attr("x", -10000).attr("y", y).attr("width", 20000).attr("height", bandH)
        .attr("fill", i % 2 === 0 ? "#0d0d0d" : "transparent").attr("pointer-events", "none");
    }
    g.append("text")
      .attr("x", STATE.mode === "global" ? -9950 : 40)
      .attr("y", y + 16)
      .attr("fill", "#1e1e1e")
      .attr("font-size", "10px")
      .attr("font-family", "'Bricolage Grotesque',sans-serif")
      .text(STATE.layerMap[layer] || "")
      .attr("pointer-events", "none");
  });

  STATE.nodes.forEach((n) => {
    if (STATE.mode === "global") {
      const idx = layerKeys.indexOf(n.layer);
      n.targetY = (layerKeys.length - 1 - idx) * bandH + bandH * 0.5;
      n.x = W * 0.1 + Math.random() * W * 0.8;
      n.y = n.targetY + (Math.random() - 0.5) * bandH * 0.2;
    } else {
      n.targetX = 0;
      n.targetY = 0;
      n.x = W * 0.5 + (Math.random() - 0.5) * 40;
      n.y = H * 0.5 + (Math.random() - 0.5) * 40;
    }
  });

  if (STATE.mode === "profile") {
    const groupByLayer = new Map(layerKeys.map((layer) => [layer, []]));
    STATE.nodes.forEach((n) => {
      groupByLayer.get(n.layer).push(n);
    });
    layerKeys.forEach((layer, i) => {
      const arr = groupByLayer.get(layer).sort((a, b) => (a.kind > b.kind ? 1 : -1));
      const x = (i + 1) * (W / (layerKeys.length + 1));
      const spacing = Math.max(70, Math.min(120, (H * 0.62) / Math.max(1, arr.length)));
      const startY = H * 0.52 - ((arr.length - 1) * spacing) / 2;
      arr.forEach((n, j) => {
        n.targetX = x;
        n.targetY = startY + j * spacing;
        n.x = n.targetX + (Math.random() - 0.5) * 20;
        n.y = n.targetY + (Math.random() - 0.5) * 20;
      });
    });
  }

  linkSel = g.append("g").selectAll("line").data(STATE.links).join("line")
    .attr("stroke", (d) => d.v >= 3 ? "rgba(232,69,60,.18)" : d.v >= 2 ? "#1e1e1e" : "#151515")
    .attr("stroke-width", (d) => d.v >= 3 ? 1.4 : d.v >= 2 ? 0.7 : 0.35)
    .attr("marker-end", "url(#a)")
    .attr("cursor", "pointer")
    .on("mouseenter", (ev, d) => { if (!STATE.lockId) showLinkTooltip(d, ev); })
    .on("mousemove", (ev) => { if (!STATE.lockId) moveTooltip(ev); })
    .on("mouseleave", () => { if (!STATE.lockId) tt.style.display = "none"; });

  particleLayer = g.append("g");

  nodeSel = g.append("g").selectAll("g").data(STATE.nodes).join("g").attr("cursor", "pointer")
    .call(d3.drag()
      .on("start", (e, d) => { if (!e.active) STATE.simulation.alphaTarget(0.06).restart(); d.fx = d.x; d.fy = d.y; })
      .on("drag", (e, d) => { d.fx = e.x; d.fy = e.y; })
      .on("end", (e, d) => { if (!e.active) STATE.simulation.alphaTarget(0); d.fx = null; d.fy = null; }));

  nodeSel.filter((d) => d.bn).append("circle").attr("r", (d) => (d.z || 10) + 5).attr("class", "bn-ring");
  nodeSel.append("circle").attr("class", "mc").attr("r", (d) => d.z || 10)
    .attr("fill", (d) => DATA.countries[d.c]?.c || "#777")
    .attr("fill-opacity", (d) => d.bn ? 0.82 : 0.35)
    .attr("stroke", (d) => d.bn ? "var(--acc)" : "#222")
    .attr("stroke-width", (d) => d.bn ? 1.4 : 0.5)
    .classed("verified-node", (d) => d.confidence && d.confidence.includes("source"));

  labelSel = nodeSel.append("text")
    .text((d) => d.l.split("\n")[0])
    .attr("dy", (d) => -(d.z || 10) - 4)
    .attr("text-anchor", "middle")
    .attr("fill", (d) => d.bn ? "#ccc" : "#666")
    .attr("font-size", (d) => d.z >= 18 ? "9px" : "7px")
    .attr("font-family", "'JetBrains Mono',monospace")
    .attr("pointer-events", "none");

  subSel = nodeSel.append("text")
    .text((d) => d.l.split("\n")[1] || "")
    .attr("dy", (d) => -(d.z || 10) + 6)
    .attr("text-anchor", "middle")
    .attr("fill", "#444")
    .attr("font-size", "6px")
    .attr("font-family", "'JetBrains Mono',monospace")
    .attr("pointer-events", "none");

  nodeSel.append("text")
    .text((d) => d.c)
    .attr("dy", (d) => (d.z || 10) + 11)
    .attr("text-anchor", "middle")
    .attr("font-size", "7px")
    .attr("fill", "#333")
    .attr("font-family", "'JetBrains Mono',monospace")
    .attr("pointer-events", "none");

  nodeSel
    .on("mouseenter", (ev, d) => {
      if (STATE.mode === "global" && d.symbol) {
        STATE.hoverSymbol = d.symbol;
        updateCompanyCard();
      }
      if (!STATE.lockId) { showTooltip(d, ev); highlightNode(d); }
    })
    .on("mousemove", (ev) => { if (!STATE.lockId) moveTooltip(ev); })
    .on("mouseleave", () => {
      if (STATE.mode === "global") {
        STATE.hoverSymbol = null;
        updateCompanyCard();
      }
      if (!STATE.lockId) { tt.style.display = "none"; resetHighlight(); }
    })
    .on("click", (ev, d) => {
      ev.stopPropagation();
      if (STATE.mode === "global" && d.symbol && DATA.profiles[d.symbol]) {
        openProfile(d.symbol);
        return;
      }
      if (STATE.lockId === d.id) {
        STATE.lockId = null;
        tt.style.display = "none";
        resetHighlight();
      } else {
        STATE.lockId = d.id;
        showTooltip(d, ev);
        highlightNode(d);
      }
    });

  svg.on("click", () => {
    if (STATE.lockId) {
      STATE.lockId = null;
      tt.style.display = "none";
      resetHighlight();
    }
  });

  STATE.simulation = d3.forceSimulation(STATE.nodes)
    .force("link", d3.forceLink(STATE.links).id((d) => d.id).distance((d) => d.v >= 3 ? 70 : 110).strength((d) => (d.v || 1) * 0.11))
    .force("charge", d3.forceManyBody().strength(STATE.mode === "global" ? -180 : -220))
    .force("x", d3.forceX((d) => STATE.mode === "global" ? W / 2 : d.targetX).strength(STATE.mode === "global" ? 0.03 : 0.25))
    .force("y", d3.forceY((d) => d.targetY).strength(STATE.mode === "global" ? 0.4 : 0.14))
    .force("collision", d3.forceCollide().radius((d) => (d.z || 10) + 8))
    .alphaDecay(0.016)
    .on("tick", () => {
      STATE.nodes.forEach((n) => {
        const m = (n.z || 10) + 12;
        const topPad = 78;
        const bottomPad = 20;
        n.x = Math.max(m, Math.min(W - m, n.x));
        n.y = Math.max(topPad + m, Math.min(H - bottomPad - m, n.y));
      });
      linkSel.attr("x1", (d) => d.source.x).attr("y1", (d) => d.source.y).attr("x2", (d) => d.target.x).attr("y2", (d) => d.target.y);
      nodeSel.attr("transform", (d) => `translate(${d.x},${d.y})`);
    });

  STATE.settleTimer = setTimeout(() => {
    if (STATE.simulation) STATE.simulation.stop();
    STATE.settleTimer = null;
  }, STATE.mode === "global" ? 7000 : 4500);

  svg.transition().duration(450).call(zoom.transform, d3.zoomIdentity.scale(0.8));
  syncUrlState();
}

export {
  svg, g, zoom, W, H, tt, labelSel, subSel,
  render, clearGraph, updateStats, buildLegend, buildLayerSidebar, buildCountryButtons,
  showTooltip, linkNodeLabel, showLinkTooltip, moveTooltip, connected, highlightNode,
  resetHighlight, highlightBy, toggleParticles, animateCounter,
};
