// Generated by Phase 01-02 extraction. Behavior-preserving move from the index.html monolith.

// Toolbar, filters, compare, modals, onboarding, search, bookmarks, top10, status, company profile.
// Owns the 7 inline-handler functions (incl. openCompanyProfile) and top-level UI wiring.
import { STATE, syncUrlState, applyUrlState, safeSaveJSON, safeReadFlag, safeWriteFlag } from "../state.js";
import {
  DATA, CREDIT_RATINGS, SEARCH_TARGETS, HQ_CITY_BY_SYMBOL, COUNTRY_CAPITAL_BY_CODE,
  escapeHtml, normalizeEntityLabel, getTopOverlap, parseYearsFromSources, computeProfileRisk, ratingText,
  getRatingsForSymbol, asCountryName, getInitials, formatMarketCap, logoCandidatesForSymbol, flagCdnCode,
} from "../data/index.js";
import {
  svg, zoom, tt, labelSel, subSel, render, highlightBy, resetHighlight, toggleParticles,
  showTooltip, showLinkTooltip, moveTooltip, highlightNode,
} from "../viz/index.js";
import { provenanceFor, renderProvenanceBadge, badgeHtml } from "../trust/index.js";
import { companyConcentration, supplierCriticality } from "../analytics/index.js";
/* global d3 */

// Cached DOM element references + module-local mutable UI state.
const loadingEl = document.getElementById("loading");
const fatalErrorEl = document.getElementById("fatalError");
const onboardingPanelEl = document.getElementById("onboardingPanel");
const ONBOARDING_STORAGE_KEY = "onboardingSeen";
const companyCard = document.getElementById("companyCard");
const cardName = document.getElementById("cardName");
const cardSymbol = document.getElementById("cardSymbol");
const cardHqText = document.getElementById("cardHqText");
const cardFlag = document.getElementById("cardFlag");
const cardFlagFallback = document.getElementById("cardFlagFallback");
const cardLogo = document.getElementById("cardLogo");
const cardLogoFallback = document.getElementById("cardLogoFallback");
const cardSuppliers = document.getElementById("cardSuppliers");
const cardServices = document.getElementById("cardServices");
const cardChannels = document.getElementById("cardChannels");
const cardRatings = document.getElementById("cardRatings");
const cardRiskBadge = document.getElementById("cardRiskBadge");
const cardRiskText = document.getElementById("cardRiskText");
const cardRiskDetails = document.getElementById("cardRiskDetails");
const cardConcentration = document.getElementById("cardConcentration");
const cardOverlap = document.getElementById("cardOverlap");
const cardTimeline = document.getElementById("cardTimeline");
const chokepointsListEl = document.getElementById("chokepointsList");
const cardSourcesBtn = document.getElementById("cardSourcesBtn");
const provenanceDrawer = document.getElementById("provenanceDrawer");
const provenanceItems = document.getElementById("provenanceItems");
const provenanceClose = document.getElementById("provenanceClose");
const mobileToggleBtn = document.getElementById("mobileToggle");
const mobileSheet = document.getElementById("mobileSheet");
const searchSuggestEl = document.getElementById("searchSuggest");
const searchHistoryEl = document.getElementById("searchHistory");
const helpModalEl = document.getElementById("helpModal");
const compareModalEl = document.getElementById("compareModal");
const methodologyModalEl = document.getElementById("methodologyModal");
const onboardingDismissEl = document.getElementById("onboardingDismiss");
const jump = document.getElementById("companyJump");
const searchInput = document.getElementById("q");

let activeModal = null;
let focusBeforeModal = null;
let logoLoadToken = 0;
let activeSuggestIndex = 0;

function showFatalError(message, detail = "") {
  if (!fatalErrorEl) return;
  const detailLine = detail ? `<br><b>Details:</b> ${String(detail)}` : "";
  fatalErrorEl.innerHTML = `<b>Application error:</b> ${String(message)}${detailLine}`;
  fatalErrorEl.style.display = "block";
  if (loadingEl) loadingEl.style.display = "none";
}

function getFocusableElements(container) {
  return [...container.querySelectorAll('button,[href],input,select,textarea,[tabindex]:not([tabindex="-1"])')]
    .filter((el) => !el.hasAttribute("disabled"));
}

function trapFocus(event, container) {
  const focusable = getFocusableElements(container);
  if (focusable.length === 0) return;
  const first = focusable[0];
  const last = focusable[focusable.length - 1];
  const isShift = event.shiftKey;

  if (isShift && document.activeElement === first) {
    event.preventDefault();
    last.focus();
  } else if (!isShift && document.activeElement === last) {
    event.preventDefault();
    first.focus();
  }
}

function openModal(modal, display = "flex") {
  if (!modal) return;
  focusBeforeModal = document.activeElement;
  modal.style.display = display;
  activeModal = modal;
  const focusable = getFocusableElements(modal);
  if (focusable[0]) focusable[0].focus();
  else modal.focus();
}

function closeModal(modal) {
  if (!modal) return;
  modal.style.display = "none";
  if (activeModal === modal) activeModal = null;
  if (focusBeforeModal && typeof focusBeforeModal.focus === "function") {
    focusBeforeModal.focus();
  }
}

function dismissOnboarding() {
  if (!onboardingPanelEl) return;
  closeModal(onboardingPanelEl);
  safeWriteFlag(ONBOARDING_STORAGE_KEY, "1");
}

function maybeShowOnboarding() {
  if (!onboardingPanelEl) return;
  if (safeReadFlag(ONBOARDING_STORAGE_KEY) === "1") return;
  openModal(onboardingPanelEl, "block");
}

function closeProvenance() {
  if (!provenanceDrawer) return;
  provenanceDrawer.style.display = "none";
}

function openProvenance() {
  const symbol = STATE.mode === "profile" ? STATE.symbol : STATE.hoverSymbol;
  if (!symbol || !DATA.profiles[symbol]) return;
  const profile = DATA.profiles[symbol];
  if (!provenanceItems) return;
  const rows = (profile.sources || []).map((src) => {
    const title = escapeHtml(src.title || src.id || "Source");
    const href = escapeHtml(src.url || "");
    return `<div class="pi"><div class="t">${title}</div>${href ? `<a href="${href}" target="_blank" rel="noopener noreferrer">${href}</a>` : ""}</div>`;
  });
  provenanceItems.innerHTML = rows.length ? rows.join("") : `<div class="cMuted">No source links in this profile.</div>`;
  provenanceDrawer.style.display = "block";
}

function setMobileSheetOpen(open) {
  if (!mobileSheet) return;
  if (open) openModal(mobileSheet, "block");
  else closeModal(mobileSheet);
}

function hideSearchPopovers() {
  if (searchSuggestEl) searchSuggestEl.style.display = "none";
  if (searchHistoryEl) searchHistoryEl.style.display = "none";
}

function renderSearchSuggestions(query) {
  if (!searchSuggestEl) return;
  const q = String(query || "").trim().toLowerCase();
  if (!q) {
    searchSuggestEl.style.display = "none";
    return;
  }
  if (searchHistoryEl) searchHistoryEl.style.display = "none";
  const suggestions = SEARCH_TARGETS
    .filter((item) => item.search.includes(q))
    .slice(0, 8);
  if (!suggestions.length) {
    searchSuggestEl.style.display = "none";
    return;
  }
  searchSuggestEl.innerHTML = suggestions
    .map(
      (item, idx) =>
        `<div class="sg-item${idx === 0 ? " on" : ""}" data-symbol="${item.symbol}" data-company="${escapeHtml(
          item.company,
        )}"><span class="sym">${item.symbol}</span><span class="cmp">${escapeHtml(
          item.company,
        )}</span></div>`,
    )
    .join("");
  searchSuggestEl.style.display = "block";
  searchSuggestEl.querySelectorAll(".sg-item").forEach((el) => {
    el.addEventListener("click", () => {
      const symbol = el.getAttribute("data-symbol");
      if (symbol && DATA.profiles[symbol]) {
        document.getElementById("q").value = symbol;
        addToSearchHistory(symbol);
        openProfile(symbol);
        hideSearchPopovers();
      }
    });
  });
}

function renderSearchHistory() {
  const sh = searchHistoryEl;
  if (!sh) return;
  if (searchSuggestEl) searchSuggestEl.style.display = "none";
  if (STATE.searchHistory.length === 0) {
    sh.style.display = "none";
    return;
  }
  sh.innerHTML = STATE.searchHistory
    .map((s) => `<div class="sh-item" data-q="${escapeHtml(s)}">${escapeHtml(s)}</div>`)
    .join("");
  sh.style.display = "block";
  sh.querySelectorAll(".sh-item").forEach((el) => {
    el.addEventListener("click", () => {
      document.getElementById("q").value = el.dataset.q;
      triggerSearch(el.dataset.q);
      hideSearchPopovers();
    });
  });
}

function addToSearchHistory(query) {
  if (!query || query.length < 2) return;
  STATE.searchHistory = STATE.searchHistory.filter(s => s !== query);
  STATE.searchHistory.unshift(query);
  STATE.searchHistory = STATE.searchHistory.slice(0, 10);
  safeSaveJSON("searchHistory", STATE.searchHistory);
  renderSearchHistory();
}

function openProfile(symbol) {
  if (!DATA.profiles[symbol]) {
    showToast(`Company ${symbol} not found`);
    return;
  }
  STATE.mode = "profile";
  STATE.symbol = symbol;
  STATE.hoverSymbol = null;
  document.getElementById("bBack").style.display = "inline-block";
  jump.value = symbol;
  closeProvenance();
  render();
  syncUrlState();
}

function transitionToProfile(symbol) {
  if (!companyCard) {
    openProfile(symbol);
    return;
  }
  companyCard.style.opacity = '0';
  companyCard.style.transform = 'translateY(8px)';
  
  setTimeout(() => {
    openProfile(symbol);
    companyCard.style.opacity = '1';
    companyCard.style.transform = 'translateY(0)';
  }, 150);
}

function openGlobal() {
  STATE.mode = "global";
  STATE.symbol = null;
  STATE.hoverSymbol = null;
  document.getElementById("bBack").style.display = "none";
  jump.value = "";
  closeProvenance();
  render();
  syncUrlState();
}

// Render (or clear) the company-card anchor provenance badge.
// Created in JS and appended next to the card name (no index.html edit).
// Guarded for the thin-JS runtime: a missing profile/anchor yields the Unknown badge.
function renderCardAnchorBadge(profile) {
  if (!cardName) return;
  let badgeEl = document.getElementById("cardNameProv");
  if (!badgeEl) {
    badgeEl = document.createElement("span");
    badgeEl.id = "cardNameProv";
    badgeEl.className = "card-name-prov";
    badgeEl.style.marginLeft = "6px";
    if (cardName.parentElement) cardName.parentElement.appendChild(badgeEl);
  }
  const sourceIndex = Object.fromEntries((profile?.sources || []).map((s) => [s.id, s]));
  const anchor = (profile?.nodes || []).find((n) => n.kind === "company") || {};
  const prov = provenanceFor(anchor, { sourceIndex, meta: DATA.meta });
  renderProvenanceBadge(badgeEl, prov);
}

function updateCompanyCard() {
  const symbol = STATE.mode === "profile" ? STATE.symbol : STATE.hoverSymbol;
  if (!symbol) {
    companyCard.style.display = "none";
    document.body.classList.remove("profile-mode");
    document.body.classList.remove("card-visible");
    closeProvenance();
    logoLoadToken += 1;
    return;
  }
  const isProfile = STATE.mode === "profile";
  const profile = DATA.profiles[symbol];
  const globalNode = DATA.nodes.find((n) => n.symbol === symbol);
  const countryCode = globalNode?.c || "XX";
  const countryName = asCountryName(countryCode);
  const city = globalNode?.hq?.city || HQ_CITY_BY_SYMBOL[symbol] || COUNTRY_CAPITAL_BY_CODE[countryCode] || "Global";

  companyCard.style.display = "block";
  document.body.classList.toggle("profile-mode", isProfile);
  document.body.classList.add("card-visible");
  cardName.textContent = profile?.company || globalNode?.company || symbol;
  cardSymbol.textContent = symbol;
  cardSymbol.style.cursor = 'pointer';
  cardSymbol.title = 'Click to copy symbol';
  cardSymbol.onclick = () => {
    navigator.clipboard.writeText(symbol).then(
      () => showToast(`Copied ${symbol}`),
      () => showToast("Clipboard unavailable"),
    );
  };
  cardHqText.textContent = `${city}, ${countryName}`;
  cardLogoFallback.textContent = String(symbol || "").replace(/[^A-Z0-9]/g, "").slice(0, 4) || "--";
  
  // Company-card anchor figure provenance badge (money/entity figure — RESEARCH Q1).
  // Derived from the company anchor node's confidence/sourceId via the trust core;
  // an unsourced/dangling anchor degrades to the honest "Unknown" badge (no fabrication).
  renderCardAnchorBadge(profile);

  // Update stats
  if (profile) {
    cardSuppliers.textContent = profile.nodes.filter(n => n.kind === 'supplier').length;
    cardServices.textContent = profile.nodes.filter(n => n.kind === 'service').length;
    cardChannels.textContent = profile.nodes.filter(n => n.kind === 'channel').length;
  } else {
    cardSuppliers.textContent = "0";
    cardServices.textContent = "0";
    cardChannels.textContent = "0";
  }
  renderCardRatings(symbol);
  renderCardInsights(symbol, profile);
  if (cardSourcesBtn) {
    cardSourcesBtn.style.display = STATE.mode === "profile" && profile ? "inline-block" : "none";
  }
  
  setCompanyLogo(symbol);

  const flagCode = flagCdnCode(countryCode);
  if (!flagCode) {
    cardFlag.style.display = "none";
    cardFlagFallback.style.display = "flex";
    cardFlagFallback.textContent = "--";
  } else {
    cardFlagFallback.style.display = "none";
    cardFlag.style.display = "block";
    cardFlag.src = `https://flagcdn.com/w80/${flagCode}.png`;
    cardFlag.srcset = `https://flagcdn.com/w80/${flagCode}.png 1x, https://flagcdn.com/w160/${flagCode}.png 2x`;
    cardFlag.onerror = () => {
      cardFlag.style.display = "none";
      cardFlagFallback.style.display = "flex";
      cardFlagFallback.textContent = countryCode;
    };
  }
}

function setCompanyLogo(symbol) {
  const token = ++logoLoadToken;
  const candidates = logoCandidatesForSymbol(symbol);
  let i = 0;
  const tryNext = () => {
    if (token !== logoLoadToken) return;
    if (i >= candidates.length) {
      cardLogo.style.display = "none";
      cardLogoFallback.style.display = "flex";
      return;
    }
    const src = candidates[i];
    i += 1;
    cardLogo.onload = () => {
      if (token !== logoLoadToken) return;
      cardLogo.style.display = "block";
      cardLogoFallback.style.display = "none";
    };
    cardLogo.onerror = () => {
      if (token !== logoLoadToken) return;
      tryNext();
    };
    cardLogo.src = src;
  };
  tryNext();
}

function renderCardRatings(symbol) {
  if (!cardRatings) return;
  const ratings = getRatingsForSymbol(symbol);
  if (!ratings) {
    cardRatings.innerHTML = '<div class="cMuted">No credit rating data available</div>';
    return;
  }
  
  const ratingHTML = [];
  
  if (ratings.spGlobal) {
    ratingHTML.push(`
      <div class="cRate">
        <span class="credit-rating sp">
          <span class="credit-rating-grade">${ratings.spGlobal.grade || 'N/A'}</span>
          <span>S&P</span>
        </span>
        <span>${ratings.spGlobal.outlook || 'Stable'}</span>
      </div>
    `);
  }
  
  if (ratings.moodys) {
    ratingHTML.push(`
      <div class="cRate">
        <span class="credit-rating moodys">
          <span class="credit-rating-grade">${ratings.moodys.grade || 'N/A'}</span>
          <span>Moody's</span>
        </span>
        <span>${ratings.moodys.outlook || 'Stable'}</span>
      </div>
    `);
  }
  
  if (ratings.fitch) {
    const fitch = ratings.fitch;
    const outlook = fitch?.longTerm?.outlook ? fitch.longTerm.outlook.replace("Rating Outlook ", "") : 'Stable';
    ratingHTML.push(`
      <div class="cRate">
        <span class="credit-rating fitch">
          <span class="credit-rating-grade">${fitch?.longTerm?.code || 'N/A'}</span>
          <span>Fitch</span>
        </span>
        <span>${outlook}</span>
      </div>
    `);
  }
  
  cardRatings.innerHTML = ratingHTML.join('') || '<div class="cMuted">No credit rating data available</div>';
}

function renderCardInsights(symbol, profile) {
  if (!profile) {
    if (cardRiskDetails) cardRiskDetails.innerHTML = "";
    if (cardConcentration) cardConcentration.innerHTML = "";
    if (cardOverlap) cardOverlap.innerHTML = "";
    if (cardTimeline) cardTimeline.innerHTML = "";
    if (cardRiskText) cardRiskText.textContent = "Open a profile to view insights.";
    if (cardRiskBadge) {
      cardRiskBadge.textContent = "N/A";
      cardRiskBadge.className = "cRiskBadge low";
    }
    return;
  }

  const risk = computeProfileRisk(profile);
  if (cardRiskBadge) {
    cardRiskBadge.className = `cRiskBadge ${risk.overall}`;
    cardRiskBadge.textContent = `${risk.overall} risk`;
  }
  if (cardRiskText) {
    cardRiskText.textContent = `${risk.suppliers} suppliers across ${risk.supplierCountries} countries`;
  }
  if (cardRiskDetails) {
    cardRiskDetails.innerHTML = [
      `<div class="cItem"><span>Supplier concentration</span><b>${risk.supplierRisk}</b></div>`,
      `<div class="cItem"><span>Geographic concentration</span><b>${risk.geoRisk}</b></div>`,
      `<div class="cItem"><span>Source-backed ratio</span><b>${Math.round(risk.sourceRatio * 100)}%</b></div>`,
    ].join("");
  }

  // Derived supplier-concentration score (DEPTH-01). Badged "Derived" — never
  // "Observed" — and links to the Methodology view for the formula + equal-weight limit.
  if (cardConcentration) {
    const c = companyConcentration(symbol, { profiles: DATA.profiles });
    if (!c) {
      cardConcentration.innerHTML = `<div class="cMuted">No concentration data available.</div>`;
    } else {
      const badge = badgeHtml(provenanceFor({ derived: true, n: c.n }, { methodologyUrl: "#methodology" }));
      cardConcentration.innerHTML =
        `<div class="cItem"><span>Supplier concentration <span class="cMuted">(HHI-based)</span></span>` +
        `<b>${c.score}/100 ${badge}</b></div>`;
    }
  }

  const overlaps = getTopOverlap(symbol, 3);
  if (cardOverlap) {
    if (!overlaps.length) {
      cardOverlap.innerHTML = `<div class="cMuted">No significant overlaps detected.</div>`;
    } else {
      cardOverlap.innerHTML = overlaps
        .map((row) => {
          const peerName = DATA.profiles[row.peer]?.company || row.peer;
          return `<div class="cItem"><span>${escapeHtml(row.peer)} ${escapeHtml(peerName)}</span><b>${row.count}</b></div>`;
        })
        .join("");
    }
  }

  const timeline = parseYearsFromSources(profile).slice(0, 5);
  if (cardTimeline) {
    if (!timeline.length) {
      cardTimeline.innerHTML = `<div class="cMuted">No dated source evidence extracted.</div>`;
    } else {
      cardTimeline.innerHTML = timeline
        .map(([year, count]) => `<div class="cItem"><span>${year}</span><b>${count} source${count === 1 ? "" : "s"}</b></div>`)
        .join("");
    }
  }
}

function exportData() {
  const data = STATE.mode === 'global' ? 
    { nodes: DATA.nodes, links: DATA.links, profiles: Object.keys(DATA.profiles).length } :
    DATA.profiles[STATE.symbol];
  
  const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = STATE.mode === 'global' ? 'supply-chain-global.json' : `supply-chain-${STATE.symbol}.json`;
  a.click();
  URL.revokeObjectURL(url);
}

function applyFilters() {
  STATE.filters.confidence = document.getElementById('fConfidence').value;
  STATE.filters.type = document.getElementById('fType').value;
  STATE.filters.verified = document.getElementById('fVerified').value;
  
  const fn = (d) => {
    let pass = true;
    if (STATE.filters.confidence !== 'all') {
      const conf = (d.confidence || '').toLowerCase();
      if (STATE.filters.confidence === 'high' && !conf.includes('high') && !conf.includes('company')) pass = false;
      if (STATE.filters.confidence === 'medium' && !conf.includes('medium') && !conf.includes('source')) pass = false;
      if (STATE.filters.confidence === 'low' && !conf.includes('low') && !conf.includes('inferred')) pass = false;
    }
    if (STATE.filters.type !== 'all' && d.kind !== STATE.filters.type) pass = false;
    if (STATE.filters.verified === 'verified' && (!d.confidence || !d.confidence.includes('source'))) pass = false;
    if (STATE.filters.verified === 'inferred' && d.confidence && d.confidence.includes('source')) pass = false;
    return pass;
  };
  
  highlightBy(fn);
  document.getElementById('filterPanel').style.display = 'none';
  syncUrlState();
}

function resetFilters() {
  document.getElementById('fConfidence').value = 'all';
  document.getElementById('fType').value = 'all';
  document.getElementById('fVerified').value = 'all';
  STATE.filters = { confidence: 'all', type: 'all', verified: 'all' };
  resetHighlight();
  document.getElementById('filterPanel').style.display = 'none';
  syncUrlState();
}

function addToCompare(symbol) {
  if (!symbol) return;
  if (STATE.compareList.includes(symbol)) {
    STATE.compareList = STATE.compareList.filter(s => s !== symbol);
  } else {
    if (STATE.compareList.length >= 3) STATE.compareList.shift();
    STATE.compareList.push(symbol);
  }
  updateCompareButton();
  if (STATE.compareList.length >= 2) {
    showCompare();
  }
  syncUrlState();
}

function updateCompareButton() {
  const symbol = STATE.mode === 'profile' ? STATE.symbol : STATE.hoverSymbol;
  const btn = document.getElementById('cardCompare');
  if (symbol && STATE.compareList.includes(symbol)) {
    btn.style.color = 'var(--acc)';
    btn.textContent = 'x';
  } else {
    btn.style.color = '#666';
    btn.textContent = '+';
  }
}

function showCompare() {
  if (STATE.compareList.length < 2) return;
  const grid = document.getElementById('compareGrid');
  grid.innerHTML = STATE.compareList.map(sym => {
    const p = DATA.profiles[sym];
    if (!p) return '';
    const rating = getRatingsForSymbol(sym);
    const fitchLabel = ratingText(rating?.fitch);
    const suppliers = p.nodes.filter(n => n.kind === 'supplier').length;
    const services = p.nodes.filter(n => n.kind === 'service').length;
    const channels = p.nodes.filter(n => n.kind === 'channel').length;
    const demand = p.nodes.filter(n => n.kind === 'demand').length;
    // Verified Entities: trust-derived (observed AND a resolving source), via the
    // centralized provenanceFor — replaces the ad-hoc .includes('source') heuristic.
    const sourceIndex = Object.fromEntries((p.sources || []).map(s => [s.id, s]));
    const verified = p.nodes.filter(n => {
      const prov = provenanceFor(n, { sourceIndex, meta: DATA.meta });
      return prov.tag === 'observed' && Boolean(prov.source);
    }).length;
    return `
      <div class="card">
        <h3>${escapeHtml(sym)} - ${escapeHtml(p.company)}</h3>
        <div class="stat"><span>Suppliers</span><b>${suppliers}</b></div>
        <div class="stat"><span>Services</span><b>${services}</b></div>
        <div class="stat"><span>Channels</span><b>${channels}</b></div>
        <div class="stat"><span>Demand Nodes</span><b>${demand}</b></div>
        <div class="stat"><span>Verified Entities</span><b>${verified}</b></div>
        <div class="stat"><span>Fitch Rating</span><b>${escapeHtml(fitchLabel)}</b></div>
        <div class="stat"><span>Category</span><b>${escapeHtml(p.category.split('(')[0].trim())}</b></div>
      </div>
    `;
  }).join('');
  openModal(compareModalEl, "block");
}

function closeCompare() {
  closeModal(compareModalEl);
}

function openMethodology() {
  openModal(methodologyModalEl, "flex");
}

function closeMethodology() {
  closeModal(methodologyModalEl);
}

// --- Critical chokepoints (DEPTH-02) -------------------------------------
// Top suppliers by real fan-in (companies depending on them), rendered into
// #chokepointsList. Every supplier label is escaped before innerHTML (T-06-03);
// fanIn is an integer from pure math.
const CHOKEPOINT_LIMIT = 8;

function getChokepoints() {
  return supplierCriticality({ profiles: DATA.profiles, limit: CHOKEPOINT_LIMIT });
}

function renderChokepoints() {
  if (!chokepointsListEl) return;
  const rows = getChokepoints();
  if (!rows.length) {
    chokepointsListEl.innerHTML = `<div class="cMuted">No chokepoints detected.</div>`;
    return;
  }
  chokepointsListEl.innerHTML = rows
    .map((row) => {
      const n = row.fanIn;
      return `<div class="cItem"><span>${escapeHtml(row.supplier)}</span>` +
        `<b>${n} compan${n === 1 ? "y" : "ies"}</b></div>`;
    })
    .join("");
}

// Highlight the chokepoint supplier nodes in the global graph. Predicate matches
// global supplier nodes whose normalized first-line label is in the chokepoint set.
function highlightChokepoints() {
  const set = new Set(getChokepoints().map((r) => r.supplier));
  highlightBy((d) =>
    d.kind === "supplier" &&
    set.has(normalizeEntityLabel((d.l || "").split("\n")[0]))
  );
}

function toggleHelp(forceOpen) {
  const isOpen = helpModalEl?.style.display === "flex";
  const shouldOpen = typeof forceOpen === "boolean" ? forceOpen : !isOpen;
  if (shouldOpen) openModal(helpModalEl, "flex");
  else closeModal(helpModalEl);
}

function triggerSearch(q, options = {}) {
  const recordHistory = options.recordHistory !== false;
  if (!q) { resetHighlight(); return; }
  if (recordHistory) addToSearchHistory(q);
  
  if (STATE.mode === "global") {
    const exact = STATE.nodes.find((n) => n.symbol?.toLowerCase() === q.toLowerCase());
    if (exact && DATA.profiles[exact.symbol]) { openProfile(exact.symbol); return; }
  }
  highlightBy((d) => (`${d.l} ${d.d} ${d.s} ${d.id}`).toLowerCase().includes(q.toLowerCase()));
}

function selectSuggestion(index) {
  if (!searchSuggestEl || searchSuggestEl.style.display === "none") return false;
  const items = [...searchSuggestEl.querySelectorAll(".sg-item")];
  if (!items.length) return false;
  const clamped = Math.max(0, Math.min(items.length - 1, index));
  items.forEach((el, i) => el.classList.toggle("on", i === clamped));
  activeSuggestIndex = clamped;
  return true;
}

function showToast(message) {
  const toast = document.createElement('div');
  toast.textContent = message;
  toast.style.cssText = `
    position: fixed;
    bottom: 60px;
    left: 50%;
    transform: translateX(-50%);
    background: var(--acc);
    color: white;
    padding: 8px 16px;
    border-radius: 4px;
    font-size: 11px;
    z-index: 2000;
    animation: fadeOut 2s forwards;
  `;
  document.body.appendChild(toast);
  setTimeout(() => toast.remove(), 2000);
}

function saveView(name) {
  if (!name) return;
  const transform = d3.zoomTransform(svg.node());
  const state = {
    mode: STATE.mode,
    symbol: STATE.symbol,
    filters: STATE.filters,
    zoom: transform.k,
    x: transform.x,
    y: transform.y,
    timestamp: Date.now()
  };
  const existing = STATE.savedViews.findIndex(v => v.name === name);
  const view = { name, state, date: new Date().toLocaleDateString() };
  if (existing >= 0) STATE.savedViews[existing] = view;
  else STATE.savedViews.push(view);
  safeSaveJSON("savedViews", STATE.savedViews);
  renderBookmarksPanel();
  showToast(`View "${name}" saved`);
}

function loadView(name) {
  const view = STATE.savedViews.find(v => v.name === name);
  if (!view) return;
  STATE.mode = view.state.mode;
  STATE.symbol = view.state.symbol;
  STATE.filters = view.state.filters;
  if (STATE.mode === 'profile' && !DATA.profiles[STATE.symbol]) {
    showToast('Profile no longer available');
    return;
  }
  render();
  svg.transition().duration(750).call(zoom.transform, d3.zoomIdentity.translate(view.state.x, view.state.y).scale(view.state.zoom));
  showToast(`Loaded "${name}"`);
  syncUrlState();
}

function deleteView(name) {
  STATE.savedViews = STATE.savedViews.filter(v => v.name !== name);
  safeSaveJSON("savedViews", STATE.savedViews);
  renderBookmarksPanel();
  showToast(`Deleted "${name}"`);
}

function renderBookmarksPanel() {
  let panel = document.getElementById('bookmarksPanel');
  if (!panel) {
    panel = document.createElement('div');
    panel.id = 'bookmarksPanel';
    panel.style.cssText = 'position:fixed;top:92px;right:12px;z-index:95;background:rgba(10,10,10,.95);border:1px solid #252525;padding:10px;display:none;max-width:280px;max-height:400px;overflow-y:auto;border-radius:4px';
    document.body.appendChild(panel);
  }
  if (STATE.savedViews.length === 0) {
    panel.innerHTML = '<div style="font-size:9px;color:#666">No saved views</div>';
    return;
  }
  panel.innerHTML = `<h3 style="font-size:9px;color:var(--dim);text-transform:uppercase;margin-bottom:8px">Saved Views</h3>` + STATE.savedViews.map(v => `<div style="display:flex;justify-content:space-between;align-items:center;padding:6px 0;border-bottom:1px solid #1a1a1a"><div style="cursor:pointer;font-size:9px;color:#aaa" onclick="loadView('${v.name}')"><b style="color:#fff">${v.name}</b><div style="color:#666;font-size:8px">${v.date} • ${v.state.mode === 'profile' ? v.state.symbol : 'Global'}</div></div><button style="background:none;border:none;color:#666;cursor:pointer;font-size:14px" onclick="deleteView('${v.name}')">&times;</button></div>`).join('');
}

function toggleBookmarks() {
  let panel = document.getElementById('bookmarksPanel');
  if (!panel) {
    renderBookmarksPanel();
    panel = document.getElementById('bookmarksPanel');
  }
  if (panel) panel.style.display = panel.style.display === 'block' ? 'none' : 'block';
}

function promptSaveView() {
  const name = prompt('Enter view name:');
  if (name) saveView(name);
}

function updateStatusIndicator() {
  const data = window.SUPPLY_MAP_DATA;
  if (!data || !data.meta || !data.meta.generatedAt) {
    document.getElementById('updateStatusText').textContent = 'Unknown';
    document.getElementById('updateStatusDot').className = 'statusDot outdated';
    return;
  }
  
  const lastUpdate = new Date(data.meta.generatedAt);
  const now = new Date();
  const daysOld = Math.floor((now - lastUpdate) / (1000 * 60 * 60 * 24));
  
  const dot = document.getElementById('updateStatusDot');
  const text = document.getElementById('updateStatusText');
  const dateEl = document.getElementById('lastUpdated');
  
  dateEl.textContent = lastUpdate.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
  
  if (daysOld <= 7) {
    dot.className = 'statusDot fresh';
    text.textContent = 'Updated';
  } else if (daysOld <= 14) {
    dot.className = 'statusDot stale';
    text.textContent = 'Aging';
  } else {
    dot.className = 'statusDot outdated';
    text.textContent = 'Outdated';
  }
}

function renderTop10List() {
  const data = window.SUPPLY_MAP_DATA;
  if (!data || !data.nodes) return;
  
  const container = document.getElementById('top10List');
  // Get top 10 companies by rank from nodes array
  const top10 = data.nodes.filter(n => n.rank).sort((a, b) => a.rank - b.rank).slice(0, 10);
  
  container.innerHTML = top10.map((company, index) => {
    const logoUrl = `https://companiesmarketcap.com/img/company-logos/64/${company.symbol}.png`;
    const rank = company.rank || index + 1;
    
    return `
      <div class="top10-item" data-symbol="${company.symbol}" onclick="openCompanyProfile('${company.symbol}')">
        <span class="rank">#${rank}</span>
        <img src="${logoUrl}" alt="${company.company}" class="logo" onerror="this.style.display='none';this.nextElementSibling.style.display='flex'">
        <div class="logoFallback" style="display:none">${getInitials(company.company)}</div>
        <div class="info">
          <div class="symbol">${company.symbol}</div>
          <div class="name">${company.company.length > 20 ? company.company.slice(0, 20) + '…' : company.company}</div>
        </div>
        <div class="marketCap">$${formatMarketCap((company.marketcap || 0) / 1e12)}</div>
      </div>
    `;
  }).join('');
  
  document.getElementById('top10Sidebar').style.display = 'block';
}

function openCompanyProfile(symbol) {
  document.getElementById('canvas').scrollIntoView({ behavior: 'smooth' });
  setTimeout(() => { openProfile(symbol); }, 500);
}

// Top-level UI wiring (event listeners, dropdown build) — runs once via main.js after imports.
function wireUI() {
  if (onboardingDismissEl) onboardingDismissEl.addEventListener("click", dismissOnboarding);
  if (helpModalEl) {
    helpModalEl.addEventListener("click", (event) => {
      if (event.target === helpModalEl) toggleHelp(false);
    });
  }
  if (compareModalEl) {
    compareModalEl.addEventListener("click", (event) => {
      if (event.target === compareModalEl) closeCompare();
    });
  }
  document.getElementById("bMethodology")?.addEventListener("click", openMethodology);
  document.getElementById("methodologyClose")?.addEventListener("click", closeMethodology);
  if (methodologyModalEl) {
    methodologyModalEl.addEventListener("click", (event) => {
      if (event.target === methodologyModalEl) closeMethodology();
    });
  }

  // Critical chokepoints panel: render the fan-in ranking + wire the graph highlight.
  renderChokepoints();
  document.getElementById("bChokepoints")?.addEventListener("click", highlightChokepoints);
  document.getElementById("bChokepointsReset")?.addEventListener("click", resetHighlight);

  DATA.nodes.sort((a, b) => a.rank - b.rank).forEach((n) => {
    const o = document.createElement("option");
    o.value = n.symbol;
    o.textContent = `${n.symbol} - ${n.company}`;
    jump.appendChild(o);
  });
  jump.addEventListener("change", () => {
    if (jump.value && DATA.profiles[jump.value]) {
      openProfile(jump.value);
    } else if (jump.value) {
      showToast(`Profile not available for ${jump.value}`);
      jump.value = "";
    }
  });

  searchInput.addEventListener("focus", () => {
    if (searchInput.value.trim()) renderSearchSuggestions(searchInput.value.trim());
    else renderSearchHistory();
  });

  searchInput.addEventListener("blur", () => {
    setTimeout(() => hideSearchPopovers(), 200);
  });

  searchInput.addEventListener("input", function () {
    const raw = this.value.trim();
    const q = raw.toLowerCase();
    STATE.lockId = null;
    tt.style.display = "none";
    if (!raw) {
      hideSearchPopovers();
      resetHighlight();
      return;
    }
    renderSearchSuggestions(raw);
    if (searchSuggestEl && searchSuggestEl.style.display !== "none") {
      selectSuggestion(0);
    }
    triggerSearch(q, { recordHistory: false });
  });

  searchInput.addEventListener("keydown", (event) => {
    if (!searchSuggestEl || searchSuggestEl.style.display === "none") {
      if (event.key === "Enter") {
        event.preventDefault();
        const value = searchInput.value.trim();
        if (value) triggerSearch(value, { recordHistory: true });
        hideSearchPopovers();
      }
      return;
    }

    const items = [...searchSuggestEl.querySelectorAll(".sg-item")];
    if (!items.length) return;
    if (event.key === "ArrowDown") {
      event.preventDefault();
      selectSuggestion(activeSuggestIndex + 1);
      return;
    }
    if (event.key === "ArrowUp") {
      event.preventDefault();
      selectSuggestion(activeSuggestIndex - 1);
      return;
    }
    if (event.key === "Enter") {
      event.preventDefault();
      const active = items[activeSuggestIndex] || items[0];
      const symbol = active?.getAttribute("data-symbol");
      if (symbol && DATA.profiles[symbol]) {
        searchInput.value = symbol;
        openProfile(symbol);
        hideSearchPopovers();
        return;
      }
      const value = searchInput.value.trim();
      if (value) triggerSearch(value, { recordHistory: true });
      hideSearchPopovers();
    }
  });

  // Keyboard shortcuts
  document.addEventListener('keydown', (e) => {
    const key = e.key.toLowerCase();
    const tag = e.target?.tagName || "";

    if (activeModal && key === "tab") {
      trapFocus(e, activeModal);
      return;
    }

    if (activeModal && key === "escape") {
      e.preventDefault();
      if (activeModal === helpModalEl) toggleHelp(false);
      else if (activeModal === methodologyModalEl) closeMethodology();
      else if (activeModal === compareModalEl) closeCompare();
      else if (activeModal === onboardingPanelEl) dismissOnboarding();
      else if (activeModal === mobileSheet) setMobileSheetOpen(false);
      return;
    }

    if (key === "escape" && provenanceDrawer?.style.display === "block") {
      e.preventDefault();
      closeProvenance();
      return;
    }

    if (tag === "INPUT" || tag === "SELECT" || tag === "TEXTAREA") return;

    // Ctrl+S / Cmd+S for save
    if ((e.ctrlKey || e.metaKey) && e.key === 's') {
      e.preventDefault();
      promptSaveView();
      return;
    }

    switch(key) {
      case 'escape':
        if (STATE.lockId) { STATE.lockId = null; tt.style.display = 'none'; resetHighlight(); }
        else openGlobal();
        break;
      case 'g': openGlobal(); break;
      case 'l': STATE.labelsVisible = !STATE.labelsVisible; labelSel.attr('opacity', STATE.labelsVisible ? 1 : 0); subSel.attr('opacity', STATE.labelsVisible ? 1 : 0); break;
      case 'f': toggleParticles(); break;
      case 'b': if (STATE.mode === "global") highlightBy((d) => d.bn); else highlightBy((d) => d.kind === "supplier" || d.kind === "risk"); break;
      case '/': e.preventDefault(); searchInput.focus(); break;
      case 'e': exportData(); break;
      case 'h': toggleHelp(); break;
    }
  });

  document.getElementById("bBack").onclick = openGlobal;
  document.getElementById("bReset").onclick = () => {
    STATE.lockId = null;
    tt.style.display = "none";
    resetHighlight();
    svg.transition().duration(450).call(zoom.transform, d3.zoomIdentity.scale(0.8));
    if (STATE.simulation) STATE.simulation.alpha(0.22).restart();
    if (STATE.settleTimer) clearTimeout(STATE.settleTimer);
    STATE.settleTimer = setTimeout(() => {
      if (STATE.simulation) STATE.simulation.stop();
      STATE.settleTimer = null;
    }, STATE.mode === "global" ? 7000 : 4500);
  };
  document.getElementById("bLabels").onclick = () => {
    STATE.labelsVisible = !STATE.labelsVisible;
    labelSel.attr("opacity", STATE.labelsVisible ? 1 : 0);
    subSel.attr("opacity", STATE.labelsVisible ? 1 : 0);
  };
  document.getElementById("bFlow").onclick = () => toggleParticles();
  document.getElementById("bBottlenecks").onclick = () => {
    if (STATE.mode === "global") highlightBy((d) => d.bn);
    else highlightBy((d) => d.kind === "supplier" || d.kind === "risk");
  };
  document.getElementById("bFilter").onclick = () => {
    const panel = document.getElementById('filterPanel');
    panel.style.display = panel.style.display === 'block' ? 'none' : 'block';
  };
  document.getElementById("bExport").onclick = exportData;
  document.getElementById("bSave").onclick = () => promptSaveView();
  document.getElementById("bBookmarks").onclick = () => toggleBookmarks();
  document.getElementById("bCompare").onclick = () => {
    if (STATE.compareList.length >= 2) showCompare();
    else alert('Select at least 2 companies to compare (use + button on company card)');
  };
  document.getElementById("bHelp").onclick = toggleHelp;
  document.getElementById("cardCompare").onclick = () => {
    const symbol = STATE.mode === 'profile' ? STATE.symbol : STATE.hoverSymbol;
    addToCompare(symbol);
  };
  if (cardSourcesBtn) cardSourcesBtn.onclick = openProvenance;
  if (provenanceClose) provenanceClose.onclick = closeProvenance;
  if (mobileToggleBtn) mobileToggleBtn.onclick = () => setMobileSheetOpen(true);
  if (document.getElementById("mobileClose")) {
    document.getElementById("mobileClose").onclick = () => setMobileSheetOpen(false);
  }

  const closeMobileAfterAction = () => {
    if (window.matchMedia("(max-width: 768px)").matches) setMobileSheetOpen(false);
  };
  const wireMobile = (id, action) => {
    const el = document.getElementById(id);
    if (!el) return;
    el.onclick = () => {
      action();
      closeMobileAfterAction();
    };
  };
  wireMobile("mBack", openGlobal);
  wireMobile("mGlobal", openGlobal);
  wireMobile("mReset", () => document.getElementById("bReset").click());
  wireMobile("mFilter", () => document.getElementById("bFilter").click());
  wireMobile("mExport", exportData);
  wireMobile("mCompare", () => document.getElementById("bCompare").click());
  wireMobile("mHelp", () => toggleHelp(true));
  wireMobile("mSave", promptSaveView);
  wireMobile("mBookmarks", toggleBookmarks);
}

export {
  applyFilters, resetFilters, closeCompare, toggleHelp, loadView, deleteView, openCompanyProfile,
  openProfile, openGlobal, updateCompanyCard, updateCompareButton, showToast, showFatalError, hideSearchPopovers,
  maybeShowOnboarding, updateStatusIndicator, renderTop10List, wireUI, jump,
  openMethodology, closeMethodology,
  renderChokepoints, highlightChokepoints,
};
